### ISSUE TITLE
Site discovery using sites/*/settings.php

### ISSUE THREAD

**Issue by jigarius** [jigarius/drall#21]
## Requirements

- Currently, Drall discovers sites defined in `sites.php`.
  - In this approach, the devs have to actively maintain the `sites.php`.
- In many cases, the `sites/*` directories have meaningful names and they don't need to be explicitly defined in `sites.php`.
- It'll be cool to have an alternate site discovery mechanism using `sites/*/settings.php`.

**If I get 15 thumbs up on the issue, I'll consider starting development.**

**Comment by hugronaphor** [comment]
If I understand correct, maybe we can merge the results of scanning `sites/*` directory and reading `$sites.php` because either of them might have not contain all possible hostnames.
+maybe strip some known directories from `sites/*` like `settings`, `default`, ...
+would also be nice to allow some technique to act as hook to manipulate the list of the sites

**Comment by jigarius** [comment]
I’d rather not mix two methods of discovery. If a user has a `sites.php`, then I’d rather assume that they are keeping it up-to-date. If the `sites.php` is missing, then Drall can use a list of all directories under `sites` that contain a `settings.php`. I’ll not work on this issue for now and let more people use Drall first.

**Comment by ericras** [comment]
My set up is that I do have a sites.php file but it only includes some sites which have custom domains.  I have sites that are not specified in sites.php that exist on the default domain in directories.  

I would only need the option to scan sites/*/settings.php to build the list of sites.

**Comment by jigarius** [comment]
@ericras have you considered adding some custom code in your `sites.php` to generate the `$sites` array to include all the sites that you have? I've done that in one project: The `sites.php` has a function that builds the `$sites` variable by going over the contents of the `sites` directory and includes some other custom logic.

```php
// Generate $sites dynamically based on presence of settings.php.
$sites = [];
foreach (glob(__DIR__ . '/*/settings.php') as $entry) {
  if (!is_file($entry)) {
    return;
  }
  
  $entry = basename(dirname($entry));
  $sites[$entry] = $entry;
}
```

**Comment by jigarius** [comment]
To keep things simple, here's the solution that I went with. To have Drall auto-detect your sites without having to actively maintain a `sites.php`,

- Create a `sites.php` based on `misc/example.sites.php` added to the project.
- This populates `$sites` based on any `settings.php` that are detected in the `sites` directory.
- Optionally, modify the contents of `$sites` based on your requirements.

With this, I'll close this issue. Please feel free to reopen it if you need more info or have any questions.
