### ISSUE TITLE
Create a Drall Launcher

### ISSUE THREAD

**Issue by golddragon007** [jigarius/drall#48]
Please create a launcher like drush or composer has, which is installed globally, then the drall is installed per project.

**Comment by jigarius** [comment]
Thanks for the idea. Use at [Symetris](https://symetris.com/) have run into the need for the [Drall Launcher](https://github.com/jigarius/drall-launcher) and development has begun.

**Comment by jigarius** [comment]
Since Drush has moved away from Drush-launcher, I've stopped work on the Drall-launcher as well. Somebody suggested a [nice alternative](https://github.com/drush-ops/drush-launcher/issues/105#issuecomment-1621097643).
