### ISSUE TITLE
How to run if installed into Drupal website project?

### ISSUE THREAD

**Issue by vaccinemedia** [jigarius/drall#88]
I have run "composer require global jigarius/drall" and then when I run the command drall I get the error "drall: command not found"

How do I run drall from the command line after installing this way? Do I instead need to run "composer global require jigarius/drall"? Or is there a different / proper way?

**Comment by jigarius** [comment]
It is no longer recommended to install Drall globally. It must be installed at the project level, just like Drush.

**Comment by vaccinemedia** [comment]
OK that's cool. IF installed at the project level, how can it be called from the command line when in the project folder without the dreaded "drall: command not found" ? Thanks!

**Comment by mortona42** [comment]
If you have your project in a container than you would need to either run the command inside it, or set up tooling to call it from outside.

**Comment by jigarius** [comment]
@vaccinemedia if you're getting a "command not found" then your terminal cannot find the correct path to the Drall executable. Try one of these 2 solutions:

- Update your `$PATHS` variable to include `/path/to/project/vendor/bin` which contains a `drall` executable.
- Run Drall with a full path, for example,
  - From anywhere: `/path/to/project/vendor/bin/drall --version`
  - From the project directory: `./vendor/bin/drall --version`

Sorry for the late reply. I was on vacation.

**Comment by jigarius** [comment]
@mortona42 I'd suggest running Drall inside the container. The idea, in this case, is to run Drall in the same environment as the rest of the Drupal project.
