### ISSUE TITLE
Support --quiet mode for suppressing Drall output

### ISSUE THREAD

**Issue by darthsteven** [jigarius/drall#91]
At the moment, I'm trying to us drall to get a nice list of the sites that it has detected and is going to run commands on, doing something like this:

```shell
echo "Listing known unique sites:"
drall exec --drall-no-progress 'echo "* @@ukey"'
```

and hoping for the output:

```
Listing known sites:
* www.example.com
* www.something.se
```

Whereas I actually get:
```
Listing known sites:
Finished: www.example.com
* www.example.com
Finished: www.something.se
* www.something.se
```

I was wondering if you'd consider introducing a 'quiet' option to the command, so that I could silence those lines that start with `Finished: `?

**Comment by jigarius** [comment]
I'll take a look at this after I stabilize Drall v3. In the meantime, have you considered using `drall site:directories` or `drall site:keys`? For all the commands that exist, please see `drall list`.

**Comment by darthsteven** [comment]
Sure, okay, that _could_ work, if there was a way to exclude the duplicates from `drall site:keys`.

**Comment by jigarius** [comment]
See if `--drall-filter` can help, e.g. `drall --drall-filter=foo site:keys`.

**Comment by darthsteven** [comment]
I've sorted it in another way. I'd argue that an option on `drall site:keys` that sets the unique option would be useful.

**Comment by jigarius** [comment]
At this point, `--drall-verbose` is replaced with `--verbose` and the old issue of Drall's `--verbose` affecting Drush's verbosity has been resolved. I revisit all code that writes to console output and decide a level of verbosity for each. This will include:
- Calls to `writeln()`
- Calls to `logger`

There is even a possibility to add in a `--quiet` mode which will hide output that is normally visible. For example, cases where the user wants to hide all Drall-specific output and see just the output of the command that is being executed.

**Comment by jigarius** [comment]
@darthsteven the feature you requested is now in 4.x.

    drall exec --no-progress --quiet 'echo "* @@ukey"'

There are many other changes and improvements in version 4.x. You are invited to try the 4.x before a stable release is made.
